### ISSUE TITLE
Migrate to New GitHub Actions

### ISSUE THREAD

**Issue by moorara** [moorara/algo#7]

**Comment by moorara** [comment]
Resolved by #9

**Comment by sobin007** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
Sleepstalker, @jcblw, @haoyh, @Demerjianm, @vincentj2, @alec-c4, @MtDeity, @Aa000888, @ruinb0w, @shuyue426, @llpliy0, @rurico, @vonKristoff, @duongthanhtung112, @1b2n3m, @jamlfy, @wuxianshishi5554, @u007, @mustafatalha, @wsnevan, @Richard-Cao, @rosejim295, @tuckerchapin, @0xdevant, @IvanChen008, @bobpozun, @Budenkinder, @chalecao, @gsfuture, @KumbleMadhu, @kioshiokamoto, @ddzyan, @zoln, @jekuer, @iamsivin, @SakuraCase, @FX777jr, @ardalanamini, @Baz1985, @devadutta, @peetck, @dalton-cole, @jamesyang124, @takeakiyamasaki, @xixileng, @chushai04, @dasibcryptoidology, @potatosalad0, @2p4g0, @AFAP52gwz, @bpmcgough, @masoncat, @jiangshanmeta, @tammy010, @PupilCrusher, @cyan92128505, @JohnCido, @oantoro, @T42Exchange, @gcnyin, @FelippeLeme, @sambacha, @zane-programs, @jaiswarabhishek, @sarnaz1304, @xbdh, @chalkedgoose, @ee99ee, @zdlldz, @Dragon1800, @bundarachada, @y9san9, @syoueicc, @yuyinws, @xiaoxianghuayu, @maticavallo, @a00012025, @ItsDarker, @jackcaldwell, @axxra, @adriendarki, @BigPineappleBigBigBig, @Trojan0523, @kroska, @wangxingkang, @kirandash, @jerry-tx, @nevrax, @phandinhhuyptit, @hiddenroadss, @WsmDyj, @adhdentropy, @cubxxw, @klamo, @JavanShen, @skport, @odrori1997, @tarun-soni, @Dariushdragonvahdani, @kissanakaen, @DrMaxis, @hahalfx, @XPlay1990, @gxkai, @burr98, @Runzeng, @pt-br, @lstar2397, @sunday2146, @qq30135878, @JiezengDev, @WinKoKoNaing, @nowakkamil, @MatteoCarminato, @debarshee2004, @luoxue-victor, @XL19860214, @loversmile, @kevinjom, @majyorika, @kuff, @ramsalinaround, @kalberto, @CCCCoder, @samonxian, @javierorbe, @ArchTaqi, @andasilva, @wuilamlaw, @kwoktung, @webhacking, @tieshucoin, @youking-lib, @AliaK000, @MountainPops, @PhearZero, @yaohaizhou, @smawpaw, @unbyte, @zhenxuans, @TomatoSoup0126, @mamadoo, @Gapur, @leejunwong, @KarlitosD, @Priyanshsharma1, @Disquse, @yakitorifoodieLazyJoke, @ahsunsay8, @Baz1985, @yangxiansheng1992, @naveen7252, @scalarwaves, @FangtaiDong10, @anzemur, @tedt10e, @anteqkois, @mojtaba-eshghie, @gofullthrottle, @anbessa14, @forshtat, @vyyq, @DenSmolonski, @Biloonov, @Kino-Zh, @thomasjeans, @treasersimplifies, @xiongzhaopeng, @akash-gajjar, @paco-ou, @ProloGSuczkO, @kingcwt, @Shadyzpop, @onepisYa, @gse7en2012, @fercgomes, @sanyu1225, @DonnC, @gseilheimer, @0rhan, @IAKGnaHz, @evelynzhang88, @Yijin19711, @developerfred, @TokenDance, @SnowJohnHash, @hayanisaid, @chenraz, @vanielf, @chayilDeborah, @pochocosta, @LuanJian, @Hanalia, @Hitekkcompany, @yzi2333, @TimothyOwen, @mizuo4wilmerboshart, @zaakirio, @wjllance, @anlakgns, @taeslee, @harry8543, @hqylss111, @dzjones26, @jamesdowen, @D-lyw, @fahidenver, @docluv, @gokulkar879, @michaelmccallam, @kuangjy2, @yukiyamamuro, @hiradfazeli, @lafronzt, @wrule, @MiguelSilvaViana, @indidatajones, @HarshitTarsariya, @aantipov, @bympi, @BlockJayn, @liubaojunsh, @jk-gan, @Chojiu15, @kucherenko, @hosseind88, @damnern12807, @Shumay14, @llyshowlee, @Seanitzel, @achmad-dodev, @ayonliu, @Valerioageno, @caxcyrbxmq46043, @sshhaatteerr, @w-zhong, @claberus, @tomwilderspin, @gigimushroom, @neethanwu, @arthurbarroso, @kaspagod, @yulecc, @codinglong, @oemerueguer, @panicdragonagusawa, @carl-lou, @michaelmccallam, @colevels, @jungai, @miladyousefzadeh2, @a1afreejk, @ibruthecreator, @XjSv, @fatihmert, @amlcodes, @Flovln, @michaelazer, @gkhan496, @VismayVora, @dbstpwlsWork32, @AbstractFear, @pmartinsesa, @limichange, @streetpresident, @pinlin168, @metadefy, @AliakbarETH, @nakam0000, @finchatftm, @AyushIyankan, @bobwbwang, @rongcui, @caeher, @ybhwang, @John-Hiroshi, @samuelweckstrom, @zerosrat, @congeeZHOU, @arag0re, @elmayana00, @wickedaf, @jspw, @kongqi404, @1harshal, @Dark15, @benemohamed, @paul0id, @fodisi, @Mr-Skully, @fudingyu, @hustnaive, @jolanhe, @beice1990, @raisiqueira
